/**
 * Snapshot Email Sender
 * 
 * Send snapshot report emails with magic links
 */

import { sendEmail, createOrUpdateContact } from './brevo-client';
import type { EmailRecipient } from './brevo-client';

/**
 * Send snapshot complete email with magic link
 * 
 * Uses the email content generated by LLM (subject + body)
 * Adds magic link and formatting
 */
export async function sendSnapshotEmail(
  email: string,
  domain: string,
  emailSubject: string,
  emailBody: string,
  magicLink: string
): Promise<{ success: boolean; error?: string }> {
  console.log(`📧 Sending snapshot email to ${email}...`);

  // Add contact to Brevo for tracking (don't fail if this fails)
  await createOrUpdateContact(email, {
    LAST_SNAPSHOT: new Date().toISOString(),
    SNAPSHOT_DOMAIN: domain,
  }).catch(err => console.warn('Failed to update contact:', err));

  // Prepare email
  const recipient: EmailRecipient = {
    email,
    name: email.split('@')[0], // Use email prefix as name
  };

  // Use the LLM-generated email body but ensure magic link is prominent
  const enhancedBody = `${emailBody}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This email was sent to ${email} because you requested a snapshot for ${domain}.

If you didn't request this, you can safely ignore this email.
The report link will expire in 30 days.

Explain My IT - Understanding your IT, one snapshot at a time
https://explainmyit.com`;

  // Convert to HTML (basic formatting)
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${emailSubject}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="white-space: pre-wrap;">${emailBody.replace(/\n/g, '<br>')}</div>
  
  <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
  
  <p style="font-size: 12px; color: #666;">
    This email was sent to ${email} because you requested a snapshot for ${domain}.
    <br><br>
    If you didn't request this, you can safely ignore this email. The report link will expire in 30 days.
    <br><br>
    <strong>Explain My IT</strong> - Understanding your IT, one snapshot at a time<br>
    <a href="https://explainmyit.com" style="color: #0066cc;">explainmyit.com</a>
  </p>
</body>
</html>`;

  // Send email
  const result = await sendEmail({
    to: [recipient],
    subject: emailSubject,
    htmlContent,
    textContent: enhancedBody,
    tags: ['tier1', 'snapshot-report', 'magic-link'],
  });

  if (result.success) {
    console.log(`✅ Snapshot email sent successfully (${result.messageId})`);
  } else {
    console.error(`❌ Failed to send snapshot email: ${result.error}`);
  }

  return result;
}

/**
 * Send welcome email (when user creates account)
 * TODO: Implement when account creation is built
 */
export async function sendWelcomeEmail(
  email: string,
  name?: string
): Promise<{ success: boolean; error?: string }> {
  console.log(`📧 Sending welcome email to ${email}...`);

  const recipient: EmailRecipient = {
    email,
    name: name || email.split('@')[0],
  };

  const subject = 'Welcome to Explain My IT!';
  
  const textContent = `Hi ${name || 'there'},

Welcome to Explain My IT! Your account is now active.

You can now:
• Save your snapshots permanently
• Run recurring snapshots (track changes over time)
• Access your dashboard anytime

View your dashboard:
https://explainmyit.com/dashboard

If you have any questions, just reply to this email.

Thanks for joining!

The Explain My IT Team
https://explainmyit.com`;

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h1 style="color: #0066cc;">Welcome to Explain My IT!</h1>
  
  <p>Hi ${name || 'there'},</p>
  
  <p>Welcome to Explain My IT! Your account is now active.</p>
  
  <p><strong>You can now:</strong></p>
  <ul>
    <li>Save your snapshots permanently</li>
    <li>Run recurring snapshots (track changes over time)</li>
    <li>Access your dashboard anytime</li>
  </ul>
  
  <p style="margin: 30px 0;">
    <a href="https://explainmyit.com/dashboard" style="display: inline-block; background: #0066cc; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px;">View Your Dashboard</a>
  </p>
  
  <p>If you have any questions, just reply to this email.</p>
  
  <p>Thanks for joining!</p>
  
  <p style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #666;">
    The Explain My IT Team<br>
    <a href="https://explainmyit.com" style="color: #0066cc;">explainmyit.com</a>
  </p>
</body>
</html>`;

  const result = await sendEmail({
    to: [recipient],
    subject,
    htmlContent,
    textContent,
    tags: ['tier1', 'welcome', 'onboarding'],
  });

  if (result.success) {
    console.log(`✅ Welcome email sent successfully (${result.messageId})`);
  } else {
    console.error(`❌ Failed to send welcome email: ${result.error}`);
  }

  return result;
}
