/**
 * Snapshot Email Sender
 * 
 * Send snapshot report emails with magic links
 */

import { sendEmail, createOrUpdateContact } from './brevo-client';
import type { EmailRecipient } from './brevo-client';

/**
 * Send snapshot complete email with magic link
 * 
 * Uses the email content generated by LLM (subject + body)
 * Adds magic link and formatting
 */
export async function sendSnapshotEmail(
  email: string,
  domain: string,
  emailSubject: string,
  emailBody: string,
  magicLink: string
): Promise<{ success: boolean; error?: string }> {
  console.log(`📧 Sending snapshot email to ${email}...`);

  // Add contact to Brevo for tracking (don't fail if this fails)
  await createOrUpdateContact(email, {
    LAST_SNAPSHOT: new Date().toISOString(),
    SNAPSHOT_DOMAIN: domain,
  }).catch(err => console.warn('Failed to update contact:', err));

  // Prepare email
  const recipient: EmailRecipient = {
    email,
    name: email.split('@')[0], // Use email prefix as name
  };

  // Use the LLM-generated email body but ensure magic link is prominent
  const enhancedBody = `${emailBody}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This email was sent to ${email} because you requested a snapshot for ${domain}.

If you didn't request this, you can safely ignore this email.
The report link will expire in 30 days.

Explain My IT - Understanding your IT, one snapshot at a time
https://explainmyit.com`;

  // Parse email body sections
  const sections = emailBody.split('\n\n');
  const introSection = sections[0] || '';
  const bodyContent = sections.slice(1).join('\n\n');
  
  // Convert to HTML with proper formatting
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${emailSubject}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f5f7fa; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
  <table role="presentation" style="width: 100%; border-collapse: collapse;">
    <tr>
      <td style="padding: 40px 20px;">
        <!-- Main Container -->
        <table role="presentation" style="max-width: 600px; margin: 0 auto; background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.08);">
          <!-- Header -->
          <tr>
            <td style="background: linear-gradient(135deg, #1f3a5f 0%, #2c5282 100%); padding: 30px; text-align: center;">
              <h1 style="margin: 0; color: white; font-size: 24px; font-weight: bold;">
                📊 Your IT Snapshot is Ready
              </h1>
              <p style="margin: 8px 0 0 0; color: #7dd3fc; font-size: 14px;">
                ${domain}
              </p>
            </td>
          </tr>
          
          <!-- Intro -->
          <tr>
            <td style="padding: 30px; background: #f8fafc;">
              <p style="margin: 0; color: #1e293b; font-size: 16px; line-height: 1.6;">
                ${introSection.replace(/\n/g, '<br>')}
              </p>
            </td>
          </tr>
          
          <!-- Main Content -->
          <tr>
            <td style="padding: 30px;">
              <div style="color: #475569; font-size: 15px; line-height: 1.7;">
                ${bodyContent.replace(/\n\n/g, '</p><p style="margin: 16px 0;">').replace(/\n/g, '<br>')}
              </div>
            </td>
          </tr>
          
          <!-- CTA Button -->
          <tr>
            <td style="padding: 0 30px 30px 30px; text-align: center;">
              <table role="presentation" style="margin: 0 auto;">
                <tr>
                  <td style="background: #1f3a5f; border-radius: 12px; padding: 16px 32px;">
                    <a href="${magicLink}" style="color: white; text-decoration: none; font-weight: 600; font-size: 16px; display: block;">
                      View Your Full Report →
                    </a>
                  </td>
                </tr>
              </table>
              <p style="margin: 12px 0 0 0; font-size: 13px; color: #64748b;">
                Or copy this link: <a href="${magicLink}" style="color: #0891b2; word-break: break-all;">${magicLink}</a>
              </p>
            </td>
          </tr>
          
          <!-- Info Box -->
          <tr>
            <td style="padding: 0 30px 30px 30px;">
              <div style="background: #ecfeff; border-left: 4px solid #06b6d4; border-radius: 8px; padding: 16px; margin-top: 20px;">
                <p style="margin: 0; color: #0e7490; font-size: 14px; line-height: 1.6;">
                  <strong>💡 Want to track changes over time?</strong><br>
                  Create a free account to save your snapshots and get automatic updates when your IT setup changes.
                </p>
              </div>
            </td>
          </tr>
          
          <!-- Footer -->
          <tr>
            <td style="padding: 24px 30px; background: #f8fafc; border-top: 1px solid #e2e8f0;">
              <p style="margin: 0 0 12px 0; font-size: 13px; color: #64748b; line-height: 1.6;">
                This email was sent to <strong>${email}</strong> because you requested a snapshot for <strong>${domain}</strong>.
              </p>
              <p style="margin: 0; font-size: 12px; color: #94a3b8; line-height: 1.5;">
                If you didn't request this, you can safely ignore this email. The report link will expire in 30 days.
              </p>
              <p style="margin: 16px 0 0 0; font-size: 12px; color: #94a3b8;">
                <strong>Explain My IT</strong> - Understanding your IT, one snapshot at a time<br>
                <a href="https://explainmyit.com" style="color: #0891b2; text-decoration: none;">explainmyit.com</a>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  // Send email
  const result = await sendEmail({
    to: [recipient],
    subject: emailSubject,
    htmlContent,
    textContent: enhancedBody,
    tags: ['tier1', 'snapshot-report', 'magic-link'],
  });

  if (result.success) {
    console.log(`✅ Snapshot email sent successfully (${result.messageId})`);
  } else {
    console.error(`❌ Failed to send snapshot email: ${result.error}`);
  }

  return result;
}

/**
 * Send welcome email (when user creates account)
 * TODO: Implement when account creation is built
 */
export async function sendWelcomeEmail(
  email: string,
  name?: string
): Promise<{ success: boolean; error?: string }> {
  console.log(`📧 Sending welcome email to ${email}...`);

  const recipient: EmailRecipient = {
    email,
    name: name || email.split('@')[0],
  };

  const subject = 'Welcome to Explain My IT!';
  
  const textContent = `Hi ${name || 'there'},

Welcome to Explain My IT! Your account is now active.

You can now:
• Save your snapshots permanently
• Run recurring snapshots (track changes over time)
• Access your dashboard anytime

View your dashboard:
https://explainmyit.com/dashboard

If you have any questions, just reply to this email.

Thanks for joining!

The Explain My IT Team
https://explainmyit.com`;

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h1 style="color: #0066cc;">Welcome to Explain My IT!</h1>
  
  <p>Hi ${name || 'there'},</p>
  
  <p>Welcome to Explain My IT! Your account is now active.</p>
  
  <p><strong>You can now:</strong></p>
  <ul>
    <li>Save your snapshots permanently</li>
    <li>Run recurring snapshots (track changes over time)</li>
    <li>Access your dashboard anytime</li>
  </ul>
  
  <p style="margin: 30px 0;">
    <a href="https://explainmyit.com/dashboard" style="display: inline-block; background: #0066cc; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px;">View Your Dashboard</a>
  </p>
  
  <p>If you have any questions, just reply to this email.</p>
  
  <p>Thanks for joining!</p>
  
  <p style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #666;">
    The Explain My IT Team<br>
    <a href="https://explainmyit.com" style="color: #0066cc;">explainmyit.com</a>
  </p>
</body>
</html>`;

  const result = await sendEmail({
    to: [recipient],
    subject,
    htmlContent,
    textContent,
    tags: ['tier1', 'welcome', 'onboarding'],
  });

  if (result.success) {
    console.log(`✅ Welcome email sent successfully (${result.messageId})`);
  } else {
    console.error(`❌ Failed to send welcome email: ${result.error}`);
  }

  return result;
}
